version: "3"

services:
  syncthing:
    image: syncthing/syncthing:2
    container_name: syncthing
    hostname: ${HOSTNAME}
    # environment:
    # - PUID=1000
    # - PGID=1000
    # - STGUIADDRESS=
    volumes:
      - ${DOCKER_DIR_PATH}/syncthing:/var/syncthing
    network_mode: host
    restart: unless-stopped
    healthcheck:
      test: curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health | grep -o --color=never OK || exit 1
      interval: 1m
      timeout: 10s
      retries: 3
